### ISSUE TITLE
The script breaks if ufw is not installed prior to running script

### ISSUE THREAD

**Issue by acezalba** [jasonheecs/ubuntu-server-setup#10]
Here's the output.log

```bash
ghost ALL=(ALL) NOPASSWD: ALL
# ssh public key redacted
sudo: ufw: command not found
```
There might need to be checks to install needed utilities before proceeding, a means to re-run the script if in case a step breaks in the process, as well as a verbose output to reassure the user that all steps were successfully executed. This was ran in a new Ubuntu 20.04 vps.

**Comment by jasonheecs** [comment]
Hi @acezalba, thanks for raising this 😄 . This issue is fixed in https://github.com/jasonheecs/ubuntu-server-setup/pull/13 by installing the `ufw` package if it's not installed.
