### ISSUE TITLE
not using password

### ISSUE THREAD

**Issue by shinokada** [jasonheecs/ubuntu-server-setup#9]
In `function addUserAccount()`, it uses `--disabled-password`.
So when you call the function, I don't think you need to use the password parameter.

Instead of this:

```
# in setup.sh line 28
addUserAccount "${username}" "${password}"
```

Shouldn't it be like this?

```
addUserAccount "${username}" 
```

And the function should be:

```
# Add the new user account
# Arguments:
#   Account Username
#   Flag to determine if user account is added silently. (With / Without GECOS prompt)
function addUserAccount() {
    local username=${1}
    local silent_mode=${2}

    if [[ ${silent_mode} == "true" ]]; then
        sudo adduser --disabled-password --gecos '' "${username}"
    else
        sudo adduser --disabled-password "${username}"
    fi

    echo "${username}" | sudo chpasswd
    sudo usermod -aG sudo "${username}"
}
```

Let me know if I missed anything.

**Comment by jasonheecs** [comment]
Hi @shinokada, thanks for raising this. You're right, given that the script sets the user to be non-password authenticated, we don't need the user to provide a password here.

I've incorporated your suggestions here: https://github.com/jasonheecs/ubuntu-server-setup/pull/12. Thanks! 😄

**Comment by scsskid** [comment]
Thanks for your script
I dont get why you would not set the new sudo users password, I understand, login auth should only be possible via ssh key, but now you cant do any sudo command?
Am I supposed to set the the new user's password right before I close the root session?
